"""Add data and dicom_metadata JSON fields to Annotation

Revision ID: 8082d55138c8
Revises: ab7cc99d5850
Create Date: 2025-07-08 09:07:41.896947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8082d55138c8'
down_revision: Union[str, None] = 'ab7cc99d5850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('data', sa.JSON(), nullable=False))
    op.add_column('annotations', sa.Column('dicom_metadata', sa.JSON(), nullable=True))
    op.drop_column('annotations', 'bounding_boxes')
    op.drop_constraint('uq_images_orthanc_project_folder', 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_images_orthanc_project_folder', 'images', ['orthanc_id', 'project_id', 'folder_id'])
    op.add_column('annotations', sa.Column('bounding_boxes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('annotations', 'dicom_metadata')
    op.drop_column('annotations', 'data')
    # ### end Alembic commands ###
